### ISSUE TITLE
Rebuild with latest rust?

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/ripgrep-feedstock#19]
### Comment:

It looks like it's _possible_ [`conda-build` long-paths-on-windows issue](https://github.com/conda/conda-build/issues/4357) might be fixable, even with the current `13.0.0` version, by rebuilding with a suitably-recent `rust`:

- https://github.com/BurntSushi/ripgrep/issues/364#issuecomment-1471122326
- https://github.com/rust-lang/rust/pull/89174

Related on conda-forge:

- https://github.com/conda-forge/staged-recipes/issues/17519

**Comment by bollwyvl** [comment]
Testing here: https://github.com/conda-forge/verapdf-feedstock/pull/1 (will rekick once CDN is happy)

**Comment by bollwyvl** [comment]
This did not fix the `conda-build` issue :crying_cat_face: But it _was_ rebuilt, and seems about 50% smaller on the wire as a `.conda`, so at least there's that.

**Comment by jakirkham** [comment]
Could you please share a reproducer in issue ( https://github.com/conda/conda-build/issues/4357 )?

**Comment by bollwyvl** [comment]
Yep, added here: https://github.com/conda/conda-build/issues/4357#issuecomment-1766458237
