### ISSUE TITLE
binutils requirement?

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/ripgrep-feedstock#3]
Noticed that there is a `binutils` requirement in this feedstock (as opposed to requiring `{{ compiler("c") }}`). Is there a reason for that? Would a PR to change this be welcome?

**Comment by jakirkham** [comment]
cc @jayfurmanek

**Comment by dbast** [comment]
The `binutils` requirement was only added to have the `strip` command available. Is there a reason to prefer `{{ compiler("c") }}` over `binutils`?

**Comment by jakirkham** [comment]
The `{{ compiler("c") }}` package already contains `binutils`.

It also makes it easier for building multiple architecture support as we already have the compiler ready to go. `binutils` OTOH is failing to build on other architectures.

**Comment by dbast** [comment]
ok. there also other updates to be done to the feedstock, which can be done via the same build number bump :)
